# -*- coding: utf-8 -*-
"""Obtención de estadisticas descriptivas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJlhiD4nsamCvFmjICOojTOJHysowxQB

Mariela Quintanar De la Mora A01642675

Valeria Aispuro Gómez A01642923

Alvaro Alejandro Cabañas Calvillo A01625742

Elius Ivan González Campos A01620856

Francisco Javier Romo Juárez A01643189

1. Carga los datos usando tu lector de csv o con pandas. Es recomendable hacerlo con pandas.
2. Verifica la cantidad de datos que tienes, las variables que contiene cada vector de datos e identifica el tipo de variables.

      La cantidad de datos en este csv son 10,000.

      Las variables contenidas en cada vector son del tipo Dtype object para la variable 'Género', y Dtype float para las variables 'Estatura' y 'Peso'.
"""

import pandas as pd

df = pd.read_csv('peso_estatura_genero.csv')
df.Estatura = df.Estatura*2.54
df.Peso = df.Peso/2.2
print(df.info())

"""3. Analiza las variables para saber que representa cada una y en que rangos se encuentran.
Si la descripción del problema no te lo indica, utiliza el máximo y el mínimo para encontrarlo.
"""

filtro_min = df[(df['Estatura'] < 150) & (df['Peso'] < 30)]
print(filtro_min.describe())
print(filtro_min)

filtro_max = df[(df['Estatura'] > 200) & (df['Peso'] < 200)]
print(filtro_max.describe())
print(filtro_max)

"""En la variable 'Estatura' el rango es de 137.828359 a 200.656806
y en la variable 'Peso' el rango es de 29.409149 a 122.72259.
"""

import numpy as np

# promedio de estatura
media_e = df['Estatura'].mean()
print('La media de estaturas es', media_e)

# mediana de estatura
mediana_e = df['Estatura'].median()
print('La mediana de estaturas es', mediana_e)

# desviación estandar de estatura
std_e = df['Estatura'].std()
print('La desviación estándar de estaturas es', std_e)

print()

# promedio de peso
media_p = (df['Peso'].mean())
print('La media de pesos es', media_p)

# mediana de peso
mediana_p = (df['Peso'].median())
print('La mediana de pesos es', mediana_p)

# desviación estandar de peso
std_p = (df['Peso'].std())
print('La desviación estándar de pesos es', std_p)


# df.groupby(['Estatura']).mean()

# Media recortada
sorted_df = df['Estatura'].sort_values()
sorted_df = sorted_df.reset_index(drop = True)
print()

p = 50
sum = 0
for i in range(p, len(sorted_df)-p):
  sum += sorted_df[i]
mean_recort = sum / (len(sorted_df)-(2*p))
print(mean_recort)

"""4. Basándose en la media, mediana y desviación estándar de cada variable, que conclusiones puedes entregar de los datos.

   De los datos anteriores podemos concluir que la estatura y el peso máximo pertenece a un hombre y la estatura y el peso mínimo pertenecen a una mujer.

   La media del peso y estatura nos proporciono una idea de cuál es el peso y estatura promedio en el conjunto de datos.  Utilizando el Índice de Masa Corporal (IMC) y basándonos en las medias de estatura (168.57) y peso (73.38), podemos concluir que la mayoría de los individuos en el archivo CSV se encuentran en la categoría de sobrepeso.

   La mediana del peso y estatura es similar a la media, esto quiere decir que los datos de peso y estatura están distribuidos de manera simétrica.

   La desviación estándar en estaturas es baja lo que indica que existe una mayor uniformidad en las estaturas mientra que en los pesos la desviación estandar es un poco más elevada lo indica una mayor variabilidad en los pesos.
"""